// Frosthaven game configuration.

import { MERCENARY_STATS } from './common.js';

const SH = { left: 41, top: 35, w: 81, h: 70 }; // single-hex, 90% of hex
const TH  = { left: 45, top: 39, w:  90, h: 156 }; // two-hex ['S'], full size
const TH8 = { left: 36, top: 24, w:  72, h: 125 }; // two-hex ['S'], 80% centred
const XH  = { left: 45, top: 39, w: 158, h: 156 }; // three-hex ['S','SE']

const TILE_ROWS = [
  {id:  1, title:'01-A', left:68, top: 39},
  {id:  2, title:'01-B', left:68, top: 39},
  {id:  3, title:'01-C', left:68, top: 39},
  {id:  4, title:'01-D', left:68, top: 39},
  {id:  5, title:'01-E', left:68, top: 39},
  {id:  6, title:'01-F', left:68, top: 39},
  {id:  7, title:'01-G', left:68, top: 39},
  {id:  8, title:'01-H', left:68, top: 39},
  {id:  9, title:'02-A', left:68, top: 39},
  {id: 10, title:'02-B', left:68, top: 39},
  {id: 11, title:'02-C', left:68, top: 39},
  {id: 12, title:'02-D', left:68, top: 39},
  {id: 13, title:'02-E', left:68, top: 39},
  {id: 14, title:'02-F', left:68, top: 39},
  {id: 15, title:'02-G', left:68, top: 39},
  {id: 16, title:'02-H', left:68, top: 39},
  {id: 17, title:'02-I', left:68, top: 39},
  {id: 18, title:'02-J', left:68, top: 39},
  {id: 19, title:'02-K', left:68, top: 39},
  {id: 20, title:'02-L', left:68, top: 39},
  {id: 21, title:'03-A', left:68, top:120},
  {id: 22, title:'03-B', left:68, top:120},
  {id: 23, title:'03-C', left:68, top:120},
  {id: 24, title:'03-D', left:68, top:120},
  {id: 25, title:'04-A', left:68, top: 77},
  {id: 26, title:'04-B', left:68, top: 77},
  {id: 27, title:'04-C', left:68, top: 77},
  {id: 28, title:'04-D', left:68, top: 77},
  {id: 29, title:'05-A', left:65, top: 77},
  {id: 30, title:'05-B', left:65, top: 77},
  {id: 31, title:'06-A', left:65, top: 39},
  {id: 32, title:'06-B', left:65, top: 39},
  {id: 33, title:'07-A', left:68, top: 39},
  {id: 34, title:'07-B', left:68, top: 39},
  {id: 35, title:'07-C', left:68, top: 39},
  {id: 36, title:'07-D', left:68, top: 39},
  {id: 37, title:'07-E', left:68, top: 39},
  {id: 38, title:'07-F', left:68, top: 39},
  {id: 39, title:'07-G', left:68, top: 39},
  {id: 40, title:'07-H', left:68, top: 39},
  {id: 41, title:'08-A', left:68, top: 77},
  {id: 42, title:'08-B', left:68, top: 77},
  {id: 43, title:'09-A', left:68, top: 77},
  {id: 44, title:'09-B', left:68, top: 77},
  {id: 45, title:'09-C', left:68, top: 77},
  {id: 46, title:'09-D', left:68, top: 77},
  {id: 47, title:'10-A', left:68, top: 39},
  {id: 48, title:'10-B', left:68, top: 39},
  {id: 49, title:'10-C', left:68, top: 39},
  {id: 50, title:'10-D', left:68, top: 39},
  {id: 51, title:'11-A', left:68, top: 39},
  {id: 52, title:'11-B', left:68, top: 39},
  {id: 53, title:'11-C', left:68, top: 39},
  {id: 54, title:'11-D', left:68, top: 39},
  {id: 55, title:'11-E', left:68, top: 39},
  {id: 56, title:'11-F', left:68, top: 39},
  {id: 57, title:'12-A', left:68, top: 77},
  {id: 58, title:'12-B', left:68, top: 77},
  {id: 59, title:'12-C', left:68, top: 77},
  {id: 60, title:'12-D', left:68, top: 77},
  {id: 61, title:'13-A', left:68, top: 39},
  {id: 62, title:'13-B', left:68, top: 39},
  {id: 63, title:'13-C', left:68, top: 39},
  {id: 64, title:'13-D', left:68, top: 39},
  {id: 65, title:'13-E', left:68, top: 39},
  {id: 66, title:'13-F', left:68, top: 39},
  {id: 67, title:'14-A', left:68, top: 77},
  {id: 68, title:'14-B', left:68, top: 77},
  {id: 69, title:'15-A', left:68, top: 35},
  {id: 70, title:'15-B', left:68, top: 35},
  {id: 71, title:'15-C', left:68, top: 35},
  {id: 72, title:'15-D', left:68, top: 35},
  {id: 73, title:'16-A', left:68, top: 39},
  {id: 74, title:'16-B', left:68, top: 39},
  {id: 75, title:'16-C', left:68, top: 39},
  {id: 76, title:'16-D', left:68, top: 39},
].map(r => ({ ...r, game: 'fh' }));

const OVERLAY_ROWS = [
  // ── Corridors ───────────────────────────────────────────────────
  { id:  1, title:'cave',           img:'cave-1',          ...SH, defaultRole:'corridor'        },
  { id:  2, title:'dungeon',        img:'dungeon-1',       ...SH, defaultRole:'corridor'        },
  { id:  3, title:'snow',           img:'snow-1',          ...SH, defaultRole:'corridor'        },
  { id:  4, title:'metal',          img:'metal-1',         ...SH, defaultRole:'corridor'        },
  { id:  5, title:'stairs',         img:'stairs',          ...SH, defaultRole:'corridor'        },
  // ── Difficult terrain ────────────────────────────────────────────
  { id:  6, title:'water',          img:'water-1',         ...SH, defaultRole:'difficult'       },
  { id:  7, title:'rubble',         img:'rubble',          ...SH, defaultRole:'difficult'       },
  { id:  8, title:'snow drift',     img:'snow-drift',      ...SH, defaultRole:'difficult'       },
  // ── Hazardous terrain ────────────────────────────────────────────
  { id:  9, title:'ice spikes',     img:'ice-spikes',      ...SH, defaultRole:'hazardous'       },
  // ── Ice terrain ──────────────────────────────────────────────────
  { id: 10, title:'ice',            img:'ice-1',           ...SH, defaultRole:'ice'             },
  // ── Wall terrain ─────────────────────────────────────────────────
  { id: 11, title:'debris',         img:'debris-1',        ...SH, defaultRole:'wall'            },
  { id: 12, title:'snow rock',      img:'snow-rock-1',     ...SH, defaultRole:'wall'            },
  { id: 13, title:'stalagmites',    img:'stalagmites',     ...SH, defaultRole:'wall'            },
  // ── Traps ────────────────────────────────────────────────────────
  { id: 14, title:'bear trap',      img:'bear-trap',       ...SH, defaultRole:'trap'            },
  { id: 15, title:'poison trap',    img:'poison-trap',     ...SH, defaultRole:'trap'            },
  { id: 16, title:'spike pit',      img:'spike-pit-trap',  ...SH, defaultRole:'trap'            },
  // ── Pressure plate ───────────────────────────────────────────────
  { id: 17, title:'pressure plate', img:'pressure-plate',  ...SH, defaultRole:'pressure-plate'  },
  // ── Obstacles ────────────────────────────────────────────────────
  { id: 18, title:'altar',          img:'altar',           ...SH, defaultRole:'obstacle'        },
  { id: 19, title:'barrel',         img:'barrel',          ...SH, defaultRole:'obstacle'        },
  { id: 20, title:'crate',          img:'crate',           ...SH, defaultRole:'obstacle'        },
  { id: 21, title:'glowing orb',    img:'glowing-orb',     ...SH, defaultRole:'obstacle'        },
  { id: 22, title:'ice pillar',     img:'ice-pillar',      ...SH, defaultRole:'obstacle'        },
  { id: 23, title:'mast',           img:'mast',            ...SH, defaultRole:'obstacle'        },
  { id: 24, title:'metal cabinet',  img:'metal-cabinet',   ...SH, defaultRole:'obstacle'        },
  { id: 25, title:'nest',           img:'nest',            ...SH, defaultRole:'obstacle'        },
  // ── 2-hex corridors ──────────────────────────────────────────────
  { id: 26, title:'cave 2',         img:'cave-2',          ...TH,  hexes:['S'], defaultRole:'corridor'  },
  { id: 27, title:'dungeon 2',      img:'dungeon-2',       ...TH,  hexes:['S'], defaultRole:'corridor'  },
  { id: 28, title:'snow 2',         img:'snow-2',          ...TH,  hexes:['S'], defaultRole:'corridor'  },
  { id: 29, title:'metal 2',        img:'metal-2',         ...TH,  hexes:['S'], defaultRole:'corridor'  },
  // ── 2-hex difficult ──────────────────────────────────────────────
  { id: 30, title:'water 2',        img:'water-2',         ...TH8, hexes:['S'], defaultRole:'difficult' },
  { id: 31, title:'log',            img:'log',             ...TH8, hexes:['S'], defaultRole:'difficult' },
  { id: 32, title:'power conduit',  img:'power-conduit',   ...TH8, hexes:['S'], defaultRole:'difficult' },
  { id: 33, title:'sarcophagus',    img:'sarcophagus',     ...TH8, hexes:['S'], defaultRole:'difficult' },
  // ── 2-hex ice ────────────────────────────────────────────────────
  { id: 34, title:'ice 2',          img:'ice-2',           ...TH8, hexes:['S'], defaultRole:'ice'       },
  // ── 2-hex walls ──────────────────────────────────────────────────
  { id: 35, title:'debris 2',       img:'debris-2',        ...TH8, hexes:['S'], defaultRole:'wall'      },
  { id: 36, title:'snow rock 2',    img:'snow-rock-2',     ...TH8, hexes:['S'], defaultRole:'wall'      },
  // ── 2-hex obstacles ──────────────────────────────────────────────
  { id: 37, title:'barricade',      img:'barricade',       ...TH8, hexes:['S'], defaultRole:'obstacle'  },
  { id: 38, title:'bookshelf',      img:'bookshelf',       ...TH8, hexes:['S'], defaultRole:'obstacle'  },
  { id: 39, title:'cave rock',      img:'cave-rock',       ...TH8, hexes:['S'], defaultRole:'obstacle'  },
  { id: 40, title:'control console',img:'control-console', ...TH8, hexes:['S'], defaultRole:'obstacle'  },
  { id: 41, title:'supply shelf',   img:'supply-shelf',    ...TH8, hexes:['S'], defaultRole:'obstacle'  },
  // ── 3-hex objects ─────────────────────────────────────────────────
  { id: 42, title:'tree',           img:'tree',            ...XH,  hexes:['S','SE'], defaultRole:'obstacle'  },
  { id: 43, title:'water 3',        img:'water-3',         ...XH,  hexes:['S','SE'], defaultRole:'difficult' },
  // ── Doors ─────────────────────────────────────────────────────────
  { id: 51, title:'cave door',      img:'cave-door',       ...SH, defaultRole:'door' },
  { id: 52, title:'dungeon door',   img:'dungeon-door',    ...SH, defaultRole:'door' },
  { id: 53, title:'metal door',     img:'metal-door',      ...SH, defaultRole:'door' },
  { id: 54, title:'snow door',      img:'snow-door',       ...SH, defaultRole:'door' },
].map(r => ({ ...r, game: 'fh' }));

const MONSTER_ROWS = [
  {id:  1, title:'abael herder'},
  {id:  2, title:'abael scout'},
  {id:  3, title:'algox archer'},
  {id:  4, title:'algox guard'},
  {id:  5, title:'algox icespeaker'},
  {id:  6, title:'algox priest'},
  {id:  7, title:'algox scout'},
  {id:  8, title:'algox snowspeaker'},
  {id:  9, title:'ancient artillery'},
  {id: 10, title:'black imp'},
  {id: 11, title:'burrowing blade'},
  {id: 12, title:'chaos demon'},
  {id: 13, title:'city guard'},
  {id: 14, title:'deep terror'},
  {id: 15, title:'earth demon'},
  {id: 16, title:'flame demon'},
  {id: 17, title:'flaming bladespinner'},
  {id: 18, title:'forest imp'},
  {id: 19, title:'frost demon'},
  {id: 20, title:'frozen corpse'},
  {id: 21, title:'harrower infester'},
  {id: 22, title:'hound'},
  {id: 23, title:'ice wraith'},
  {id: 24, title:'lightning eel'},
  {id: 25, title:'living bones'},
  {id: 26, title:'living doom'},
  {id: 27, title:'living spirit'},
  {id: 28, title:'lurker clawcrusher'},
  {id: 29, title:'lurker mindsnipper'},
  {id: 30, title:'lurker soldier'},
  {id: 31, title:'lurker wavethrower'},
  {id: 32, title:'night demon'},
  {id: 33, title:'ooze'},
  {id: 34, title:'piranha pig'},
  {id: 35, title:'polar bear'},
  {id: 36, title:'rending drake'},
  {id: 37, title:'robotic boltshooter'},
  {id: 38, title:'ruined machine'},
  {id: 39, title:'savvas icestorm'},
  {id: 40, title:'savvas lavaflow'},
  {id: 41, title:'shrike fiend'},
  {id: 42, title:'snow imp'},
  {id: 43, title:'spitting drake'},
  {id: 44, title:'steel automaton'},
  {id: 45, title:'sun demon'},
  {id: 46, title:'vermling priest'},
  {id: 47, title:'vermling scout'},
  {id: 48, title:'wind demon'},
  // Bosses
  {id:101, title:'algox stormcaller',             boss:true},
  {id:102, title:'elder ooze',                    boss:true},
  {id:103, title:'fish king',                     boss:true},
  {id:104, title:'fracture of the deep',          boss:true},
  {id:105, title:'frozen fist',                   boss:true},
  {id:106, title:'harbinger of shadow',           boss:true},
  {id:107, title:'lord of chaos',                 boss:true},
  {id:108, title:'prince of frost',               boss:true},
  {id:109, title:'program director',              boss:true},
  {id:110, title:'render',                        boss:true},
  {id:111, title:'seeker of the abyss',           boss:true},
  {id:112, title:'snowdancer',                    boss:true},
  {id:113, title:'the collector',                 boss:true},
  {id:114, title:'the orphan',                    boss:true},
  {id:115, title:'the relic',                     boss:true},
  {id:116, title:'vestige of the imprisoned god', boss:true},
].map(r => ({ ...SH, boss: false, game: 'fh', ...r }));

// ─── Level-dependent stats ────────────────────────────────────────────────────

// Monster level stats: {monsterId: {level: {maxHp, xp}}}
const MONSTER_STATS = {
  // Example: Abael Herder (id: 1)
  1: {
    0: { maxHp: 4, xp: 40 },
    1: { maxHp: 5, xp: 50 },
    2: { maxHp: 6, xp: 60 },
    3: { maxHp: 7, xp: 70 },
    4: { maxHp: 8, xp: 80 },
    5: { maxHp: 9, xp: 90 },
    6: { maxHp: 10, xp: 100 },
    7: { maxHp: 11, xp: 110 },
  },
  // Add more monsters as needed. Template:
  // 2: {
  //   0: { maxHp: X, xp: Y },
  //   ...levels...
  // },
};

export default {
  id: 'fh',
  name: 'Frosthaven',
  gridSize: { cols: 40, rows: 51 },
  tiles: TILE_ROWS,
  overlays: OVERLAY_ROWS,
  monsters: MONSTER_ROWS,
  monsterStats: MONSTER_STATS,
  mercenaryStats: MERCENARY_STATS,
};
